title = "Visualizing the 1001 Nights"
visualization_title = "Visualization"
input_title = "Directory of Stories"
bg_color = "#383A54"
colorscale = "darkmint"
mint = "#C6F2CF"
male = "#EDE7FF"
female = "#F7E9CD"